faster move speed
vgstation-coders/vgstation14 pull request #3
Opened 2024-12-19 04:40 UTC by CrazyAmphibian

## what this does
increase base move speed from 4.5/2.5 -> 7.0/4.0, or about 55% faster runing, and 60% faster walking

https://github.com/user-attachments/assets/24ea68cf-a9a0-408d-9fd3-49b0cc211f84

## why it's good
brings the move speed more in line with /vg/station's normal move speed - aka, fast.

## how it was tested
booted up local server, i was faster.

**Changelog**

:cl:
- tweak: increased base move speed

2024-12-20 15:34 UTC, west3436 commented
sanic

2024-12-20 22:57 UTC, GroggleG commented
Is /VG/ speed similar to /TG/? Trying to figure out their speed.

2024-12-21 05:09 UTC, BasedUser requested changes

2024-12-23 03:47 UTC, CrazyAmphibian commented on Content.Shared/Movement/Components/MovementSpeedModifierComponent.cs
> +        public const float DefaultBaseSprintSpeed = 7.0f;
solved

2024-12-23 03:51 UTC, merged