WIP: restore sprites
vgstation-coders/vgstation14 pull request #8
Opened 2024-12-22 05:23 UTC by Inorien

## About the PR

getting rid of the shit sprites

## Why / Balance

becaus their shit

## Technical details

replacing with the proper ones

## Media
![image](https://github.com/user-attachments/assets/cfc882e5-ffe4-4cab-899c-9bb240a9588a)
![image](https://github.com/user-attachments/assets/6edce125-49a4-4f76-b4cb-919442eb990b)
![image](https://github.com/user-attachments/assets/014db32e-037d-4732-8d91-c090dbacd4b4)

more to come

2024-12-23 13:09 UTC, Inorien commented
all our machines are in (with properly timed animations), there are a few weird ones in the base code (shit like a uniform vendor for every single department) that we're more likely to be removing rather than respriting
did a fuckton of objects too, atmos analyser and health analyser in particular have a couple of "added features"
walking around the dev area there are so many machines that stand out as still-to-do, i'm going to get on those next but if you want to merge this as-is i'm going to continue with them regardless

2024-12-24 19:57 UTC, west3436 requested changes
Thanks for all the great effort you put into this! Only request is to remove the cash sprite replacement since it pretty much breaks the functionality of cash and we'll be having a playtest soon. Better to get it fixed in code when we update the sprites

2024-12-25 01:08 UTC, Inorien commented
remaining TODO

> Thanks for all the great effort you put into this! Only request is to remove the cash sprite replacement since it pretty much breaks the functionality of cash and we'll be having a playtest soon. Better to get it fixed in code when we update the sprites

trade offer: i revert the cash sprites but only modify the colours to match our denominations
e.g. 1 is purple for us but green on base, which is our 100, but base 100 is black, which is our 1000, which is orange on base... which is our 10, which is blue on base...

2024-12-25 13:42 UTC, west3436 approved these changes

2024-12-25 13:43 UTC, merged